#!/bin/sh
#set -x
#sshkeper 0.1 stub
# testing debian 7.1, Mac OS X 10.8.4
stubid='11e147c678fd44fada054745e31d7492'
enc='openssl enc -e -base64 -aes-256-cfb'
dec='openssl enc -d -base64 -aes-256-cfb'
compression='-z' #
prefix="$HOME/.ssh"
self="$0"

selfpkg(){
    action=$1
    if test "$action" = "c" ; then
        tar -C "$prefix" "-$action" "$compression" -vf- "."
    else
        tar -C "$prefix" "-$action" "$compression" -vf- #"$2"
    fi
}

stubline(){
i=0 #число строк в stub
# вычисления числа строк
while read line           
do           
    i=`expr $i + 1`    
    if test "$line" = "#$stubid"; then break; fi
done < $self
echo $i
}


# помощь
usage(){
cat << EOH >&2
Usage:
  $self [options]"

Application Options:
  -p    path prefix
  -x    extract
  -u    update
  -c    create
  -d    diff
  -t    list 
  -h    help

Version id: $stubid
Licence: MIT
EOH
}

if test "$#" -eq 0 ; then usage;exit 1;fi

set -- $(getopt xctdp:h "$@")

while test $# -gt 0
do
    case "$1" in
       -x) extflag=y;;
       -c) createflag=y;;
       -t) listflag=y;;
       -d) diffflag=y;;
       -p) prefix="$2";shift;;
       -h) usage "$0";;
       --) shift;break;;
       -*) usage "$0";;
        *) break;;
    esac
    shift
done

line=`stubline`
offset=`head -n $line "$self" | wc -c | tr -d " "`

if test "$createflag" = "y" ; then
    selfpkg c 2>/dev/null | eval $enc | dd of="$self" obs="$offset" seek=1 2>/dev/null
fi

if test "$extflag" = "y" ; then
    if ! test -d "$prefix" ; then  mkdir -p "$prefix"; fi     
    dd if="$self" ibs="$offset" skip=1 2>/dev/null | eval "$dec" | selfpkg x
fi

if test "$listflag" = "y" ; then
    dd if="$self" ibs="$offset" skip=1 2>/dev/null | eval "$dec" | selfpkg t
fi

if test "$diffflag" = "y" ; then
    dd if="$self" ibs="$offset" skip=1 2>/dev/null | eval "$dec" | selfpkg d
fi 

exit 0
#11e147c678fd44fada054745e31d7492
